import { User, Service, UrgentNeed, TopEarner, Category, Order } from './types';

export const INITIAL_USER: User = {
  name: 'Emmanuel Appiah',
  phone: '050 000 0000',
  department: 'Computer Science',
  year: 'Year 3',
  profileImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
  isVerified: true,
  earnedGHS: 1450,
  completedJobsCount: 12,
};

export const CATEGORIES: Category[] = [
  { id: 'it', name: 'IT Services', icon: 'Laptop' },
  { id: 'tutoring', name: 'Tutoring', icon: 'BookOpen' },
  { id: 'food', name: 'Food Delivery', icon: 'Utensils' },
  { id: 'fashion', name: 'Fashion', icon: 'Shirt' },
  { id: 'printing', name: 'Printing', icon: 'Printer' },
  { id: 'repairs', name: 'Repairs', icon: 'Wrench' },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 's1',
    title: 'Full OS & Software Installation',
    description: 'Professional operating system installation (Windows/Linux/macOS), recovery, driver setup, and core course software setup like Matlab, Visual Studio, Android Studio, and office tools. Quick turnaround on campus.',
    category: 'it',
    price: 120,
    priceType: 'fixed',
    rating: 4.9,
    reviewsCount: 24,
    sellerName: 'Kofi Mensah',
    sellerDept: 'Computer Science',
    sellerImage: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
    urgent: false,
    timestamp: '2026-06-10T12:00:00Z',
  },
  {
    id: 's2',
    title: 'Calculus & Algebra Peer Tutor',
    description: 'Struggling with maths? I offer private 1-on-1 tutoring or group study reviews for core math modules. Very patient, includes past exam papers walkthrough and clear conceptual breakdowns.',
    category: 'tutoring',
    price: 25,
    priceType: 'hourly',
    rating: 5.0,
    reviewsCount: 12,
    sellerName: 'Araba Baidoo',
    sellerDept: 'Applied Mathematics',
    sellerImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500',
    urgent: false,
    timestamp: '2026-06-09T08:30:00Z',
  },
  {
    id: 's3',
    title: 'Home-made Jollof & Grill',
    description: 'Hot, spicy, and extremely delicious student-priced home-style Ghana Jollof! Available with spicy grilled chicken, salad, shito, and plantains. Clean, fresh, and delivered right to your hostel room.',
    category: 'food',
    price: 35,
    priceType: 'fixed',
    rating: 4.7,
    reviewsCount: 56,
    sellerName: 'Priscilla Owusu',
    sellerDept: 'Business Administration',
    sellerImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500',
    urgent: false,
    timestamp: '2026-06-10T14:20:00Z',
  },
  {
    id: 's4',
    title: 'Custom Campus Hoodies',
    description: 'Heavyweight custom screen-printed and embroidered hoodies with high-quality local materials. Choose from a selection of custom campus graphics or submit your own custom design for clubs, cohorts, and friends.',
    category: 'fashion',
    price: 80,
    priceType: 'fixed',
    rating: 4.8,
    reviewsCount: 104,
    sellerName: 'Sarkodie',
    sellerDept: 'Fashion Design',
    sellerImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=500',
    urgent: false,
    timestamp: '2026-06-08T16:45:00Z',
  },
  {
    id: 's5',
    title: 'Fast Lecture Slides Printing & Binding',
    description: 'Bulk lecture slide printing, document binding, laminating, and delivery directly to your lecture hall or hostel. Competitive rates for whole classes or associations! Direct PDF imports.',
    category: 'printing',
    price: 0.50,
    priceType: 'hourly', // per page
    rating: 4.9,
    reviewsCount: 38,
    sellerName: 'John Dumelo',
    sellerDept: 'Engineering',
    sellerImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1562654501-a0ccc0fc3fb1?w=500',
    urgent: false,
    timestamp: '2026-06-11T01:10:00Z',
  },
  {
    id: 's6',
    title: 'Smartphone & Fan Repairs',
    description: 'Cracked screen replacements, charging port repairs, speaker updates, and desk fan electrical fixing. Let an experienced engineering student revive your electronic gears at a fraction of the market price.',
    category: 'repairs',
    price: 50,
    priceType: 'fixed',
    rating: 4.6,
    reviewsCount: 19,
    sellerName: 'Kojo Antwi',
    sellerDept: 'Electrical Engineering',
    sellerImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500',
    urgent: false,
    timestamp: '2026-06-10T10:05:00Z',
  },
];

export const INITIAL_URGENT_NEEDS: UrgentNeed[] = [
  {
    id: 'u1',
    title: 'Deliver food from Main Gate',
    description: 'Need someone to pick up hot food parcel from standard security checkpoint at Main Gate and drop it to Hostel B, 3rd Floor. Delivery needed ASAP as foods getting cold!',
    budget: 15.00,
    timeLeftText: '14m left',
    timestamp: new Date(Date.now() + 14 * 60 * 1000).toISOString(),
    posterName: 'Grace Mensah',
    posterDept: 'Applied Arts',
    posterImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    accepted: false,
    acceptedBy: null
  },
  {
    id: 'u2',
    title: 'Lab Report Formatting',
    description: 'Help format a LaTeX computer science lab report according to strict style sheets. Assignment deadline tomorrow morning 8 AM.',
    budget: 40.00,
    timeLeftText: '2h left',
    timestamp: new Date(Date.now() + 120 * 60 * 1000).toISOString(),
    posterName: 'Bright Osei',
    posterDept: 'Computer Science',
    posterImage: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    accepted: false,
    acceptedBy: null
  },
  {
    id: 'u3',
    title: 'Need Urgent Presentation Clicker',
    description: 'Rental presentation clicker needed for my final defense presentation at 2 PM today in Building A Auditorium.',
    budget: 10.00,
    timeLeftText: '4h left',
    timestamp: new Date(Date.now() + 240 * 60 * 1000).toISOString(),
    posterName: 'Selasi K.',
    posterDept: 'Business',
    posterImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    accepted: false,
    acceptedBy: null
  }
];

export const TOP_EARNERS: TopEarner[] = [
  { rank: 1, name: 'Kofi M.', department: 'Computer Science', amount: 4200 },
  { rank: 2, name: 'Sandra A.', department: 'Applied Arts', amount: 3850 },
  { rank: 3, name: 'Emmanuel O.', department: 'Engineering', amount: 2900 },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'o1',
    title: 'Full OS & Software Installation',
    price: 120,
    priceType: 'fixed',
    sellerName: 'Kofi Mensah',
    buyerName: 'Emmanuel Appiah',
    status: 'completed',
    timestamp: '2026-06-08T10:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=500',
  },
  {
    id: 'o2',
    title: 'Calculus & Algebra Peer Tutor',
    price: 25,
    priceType: 'hourly',
    sellerName: 'Araba Baidoo',
    buyerName: 'Emmanuel Appiah',
    status: 'in_progress',
    timestamp: '2026-06-10T15:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500',
  }
];
